### PR TITLE
Check for messages length before logging.

### LINKED ISSUE #256: v6.1.0 prints empty lines
This is a regression of #244.

With 6.1.0: https://travis-ci.org/twbs/bootstrap/jobs/475278409#L666-L695
With 6.0.1: https://travis-ci.org/twbs/bootstrap/jobs/475230811

It seems to me there must be a check before `console.warn`.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #256 

It doesn't seem to be tests for this, so I hope this doesn't break anything inadvertently.

/CC @RyanZim

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -235,13 +235,15 @@ function css(css, file) {
               chalk`{green Finished {bold ${relativePath}} in {bold ${prettyTime}}}`
             )
 
-            console.warn(
-              reporter(
-                Object.assign({}, result, {
-                  messages: result.warnings()
-                })
+            if (result.messages.length) {
```
Comment (RyanZim) [inline index.js]: Shouldn't this be `result.warnings().length`? Otherwise, if there's non-warning messages, empty lines will still be printed.

While we're at it, might as well assign `result.warnings()` to a `const` so we don't have to make the call twice.

Comment (XhmikosR) [reply index.js]: You know the codebase better, I thought to just check for warnings but I thought that #256 changed this on purpose to include all messages.

**Comment by XhmikosR** [comment]
@RyanZim: please check the second patch and let me know.

**Comment by RyanZim** [comment]
Published in v5.1.1 :tada:
